// <auto-generated />
using System;
using Clima.Cidade.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clima.Cidade.Api.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Clima.Cidade.Api.Models.ClimaCidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(80) CHARACTER SET utf8mb4")
                        .HasMaxLength(80);

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("TemperaturaAtual")
                        .HasColumnType("double");

                    b.Property<double>("TemperaturaMax")
                        .HasColumnType("double");

                    b.Property<double>("TemperaturaMin")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("ClimaCidades");
                });
#pragma warning restore 612, 618
        }
    }
}
